DROP TABLE IF EXISTS comments_tree;
DROP TABLE IF EXISTS users_comments;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS post_blog;
DROP TABLE IF EXISTS blogs;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;